### ISSUE TITLE
能否直接自动匹配vuln的检测脚本自动检测漏洞

### ISSUE THREAD

**Issue by safebaseline** [WyAtu/Perun#1]
能否直接自动匹配vuln的检测脚本自动检测漏洞

**Comment by WyAtu** [comment]
--search/--filter/--exclude几个参数中的一个或者多个配合使用，可以完成vuln筛选，然后进行默认配置(如端口、字典)的扫描，[使用举例](https://github.com/WyAtu/Perun/blob/master/doc/how2start.md#%E4%BD%BF%E7%94%A8%E4%B8%BE%E4%BE%8B)，比如在内网渗透中，直接使用`Perun -l . -t target --search innet`，即会扫描常见端口，然后根据端口开放情况自动扫描相应漏洞。
