### ISSUE TITLE
使用中遇到的坑

### ISSUE THREAD

**Issue by keyeee0** [WyAtu/Perun#10]
在使用python3版本运行此工具时，提示以下报错
ImportError: cannot import name 'urlopen' from 'urllib'

经过分析发现，在从Python 2向Python 3迁移的过程中， urllib的包重新进行了设计和调整，故两者在不同的Python下是不兼容的。
在Python 3下正确的用法是：  
from urllib.request import urlopen

**Comment by WyAtu** [comment]
本来就是py2的项目哈，Readme也是这么写的
